apiVersion: apps/v1
kind: Deployment
metadata:
  name: svelte-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svelte-app
  template:
    metadata:
      labels:
        app: svelte-app
    spec:
      containers:
      - name: svelte-app
        image: hub.docker.com/repository/docker/emerjayd/svelte-app-docker:latest
        ports:
        - containerPort: 5000
